JWT_SECRET:
  'golang-zt-server-prod'
JWT_COOKIE_VERIFY:
  'false'
COOKIE_SALT:
  'golang-zt-server-test-for-cookie-salt'

APP_PORT:
  ':3000'
APP_ENV:
  'prod'
PROJECT_NAME:
  'default'
SENSITIVE_KEY:
  ''
EVENT_OUTPUT_PATH:
  ''
WRITE_SWAGGER:
  'false'

MYSQL_USERNAME:
  'zt-server'
MYSQL_PASSWORD:
  ''
MYSQL_DATABASE:
  'go'
MYSQL_WRITER_PORT:
  '3306'
MYSQL_WRITER_HOST:
  ''
MYSQL_READER_PORT:
  '3306'
MYSQL_READER_HOST:
  ''

REDIS_HOST:
  ''
REDIS_PORT:

REDIS_PASSWORD:
  ''
REDIS_DB:
  0

TENCENT_CAPTCHA_SECRET_KEY:
  ''
TENCENT_CAPTCHA_SECRET_ID:
  ''
TENCENT_CAPTCHA_APP_ID:
  0
TENCENT_CAPTCHA_APP_SECRET:
  ''
MONTNETS_SMS_USER_ID:
  ''
MONTNETS_SMS_PWD:
  ''
MONTNETS_SMS_API_KEY:
  ''
MONTNETS_SMS_HOST:
  ''
MONTNETS_SMS_PORT:
  ''